### ISSUE TITLE
Have single video-record button

### ISSUE THREAD

**Issue by paddy-r** [paddy-r/BirdCam#22]
Currently two buttons for "start recording" and "stop recording". Only needs to be one. Rough jobs:

* [x] Change first button label and functionality upon pressing -> toggle between start and stop recording -> done in #25
* [x] Once functionality copied over to first button, remove second button -> done in #25
* [x] Buttons not aligned properly -> done in #26
* [x] Check all default video/image arguments defined and used as attributes in ```BirdCam``` object -> done in #26
* [ ] Also limit recording time to (say) one minute

**Comment by paddy-r** [comment]
Reopening as not quite complete.

**Comment by paddy-r** [comment]
Reopening as not complete.
